- name: rpm psql
  shell: rpm -ivh --nodeps https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

- name: copy pgdg-redhat-all.repo
  copy:
    src: "roles/common/files/pgdg-redhat-all.repo"
    dest: "/etc/yum.repos.d/"
    backup: no
    owner: root
    group: root
    mode: 0644

- name: install common package
  yum:  pkg={{item}} state=latest
  loop:
    - gcc
    - gcc-c++
    - git
    - nmap
    - libselinux-python
    - wget
    - openssl-devel
    - readline-devel
    - htop
    - postgresql12

- name: set a hostname
  hostname:
    name: "{{ hostname }}"
